import {localDate} from '../catalog.js';
import {monthlySummary,percent} from '../analytics.js';
import {heading,escapeHTML as h} from '../ui.js';
export function table(headers,rows) {return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th scope="col">${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((v,i)=>i?`<td>${h(v)}</td>`:`<th scope="row">${h(v)}</th>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">該当する記録はありません。</td></tr>`}</tbody></table></div>`;}
export function renderDashboard({root,repo},month=localDate().slice(0,7)) {
  const s=monthlySummary(repo.snapshot(),month);
  root.innerHTML=`${heading('MONTH / 月間ダッシュボード','1か月の活動を見渡す。','提案・引継ぎ・最終結果を、それぞれの指標で確認します。')}<label class="field">対象月<input type="month" id="dashboard-month" value="${h(month)}" required></label>
  <section class="card"><h2>接客から最終結果までの活動</h2><p class="muted fine">独立した件数です。引継ぎを経由しない成約や、提案のない指名購入もあります。左から順に人数が減る図ではありません。</p><div class="activity-grid">${[['接客件数',s.total],['Panasonic提案件数',s.proposed],['店舗引継ぎ件数',s.handoff],['Panasonic成約件数',s.panasonic]].map(([name,n],i)=>`<div><span class="eyebrow">${['接客','提案','引継ぎ（任意）','最終結果'][i]}</span><strong>${n}<small>件</small></strong><span>${name}</span></div>`).join('')}</div></section>
  <section class="stats daily-stats"><div><span>勤務日数（同日を重複しない）</span><strong>${s.days}<small>日</small></strong></div><div><span>勤務時間（休憩を除く）</span><strong>${s.shifts&&s.incompleteShifts===s.shifts?'—':`${Math.floor(s.minutes/60)}:${String(s.minutes%60).padStart(2,'0')}`}</strong><small>時間:分 · 未入力 ${s.incompleteShifts}勤務</small></div><div><span>Panasonic提案率</span><strong>${percent(s.proposed,s.total)}</strong></div><div><span>Panasonic成約率（全接客）</span><strong>${percent(s.panasonic,s.total)}</strong></div><div><span>提案からのPanasonic成約率</span><strong>${percent(s.proposedWon,s.proposed)}</strong></div><div><span>引継ぎ有無の未記録</span><strong>${s.handoffUnknown}<small>件</small></strong></div></section>
  <details class="card"><summary>集計式と数え方</summary><div class="detail-content"><p>提案率＝Panasonic提案件数 ÷ 全接客件数 × 100</p><p>Panasonic成約率（全接客）＝Panasonic成約件数 ÷ 全接客件数 × 100</p><p>提案からの成約率＝提案あり・Panasonic成約の両方に当てはまる接客件数（${s.proposedWon}件） ÷ Panasonic提案件数 × 100</p><p>分母0件は「—」。割合は小数点1桁に丸めます。提案有無が未記録の${s.proposalUnknown}件も全接客の分母に含めるため、過去データが未記録だと提案率は低めになります。</p><p>勤務は勤務開始日、接客は接客日で対象月を判定。勤務時間は入力済み分の合計です。後日結果を更新すると元の接客月の集計に反映されます。</p></div></details>
  <div class="dashboard-columns"><section class="card"><h2>最終的な接客結果</h2>${table(['結果','接客件数'],s.outcomes)}</section><section class="card"><h2>引継ぎ後の現在の結果</h2>${table(['結果','接客件数'],s.handoffOutcomes)}</section></div>
  <section class="card"><h2>カテゴリー別</h2><p class="muted fine">同じ接客の同じカテゴリーは1件。成約列は「Panasonic成約となった接客に含まれるカテゴリー」です。複数商品で個別の成約を断定する値ではありません。カテゴリー間では重複します。</p>${table(['カテゴリー','接客件数','Panasonic成約接客'],s.categories)}</section>
  <div class="dashboard-columns"><section class="card"><h2>Panasonic型番別成約件数</h2><p class="muted fine">Panasonic成約接客の「購入型番」を使用。同じ接客・同じ型番は1件。他社メーカーを明記した明細は除外し、メーカー空欄の明細は接客結果からPanasonicとして扱います。数量の合計ではありません。</p>${table(['購入型番','接客件数'],s.models)}</section><section class="card"><h2>他社成約のメーカー別</h2><p class="muted fine">他社成約の接客が対象。同じ接客・同じメーカーは1件。表記の異なるメーカー名は別集計です。</p>${table(['メーカー','接客件数'],s.manufacturers)}</section></div>
  <div class="dashboard-columns"><section class="card"><h2>理由別の接客件数</h2><p class="muted fine">Panasonic成約以外の接客が対象。複数選択は各理由に1件ずつ計上。理由未入力：${s.reasonsMissing}件。</p>${table(['理由','接客件数'],s.reasons)}</section><section class="card"><h2>要因別の接客件数</h2><p class="muted fine">同じ接客の同じ要因は1件。要因が複数なら各分類に計上します。未入力と未分類は別です。</p>${table(['要因','接客件数'],s.factors)}</section></div>
  <section class="card"><h2>学習課題の状態</h2><p class="muted fine">選択月に作成した課題の現在の状態です。月末時点の履歴ではありません。作成日時がない旧課題は月別に含めません。</p>${table(['状態','課題件数'],s.learning)}</section>`;
  root.querySelector('#dashboard-month').addEventListener('change',event=>{const value=event.target.value;if(value)location.hash=`#dashboard/${value}`;else event.target.value=month;});
}
