import {ALL_CATEGORIES,OUTCOMES} from '../catalog.js';
import {filterEncounters} from '../analytics.js';
import {heading,escapeHTML as h} from '../ui.js';
import {encounterList} from './home.js';
export function renderHistory({root,repo}) {
  const db=repo.snapshot(),stores=[...new Set(db.shifts.map(s=>s.storeAlias))];
  const options=list=>list.map(([id,text])=>`<option value="${h(id)}">${h(text)}</option>`).join('');
  root.innerHTML=`${heading('HISTORY / 過去の記録','接客を探す・追記する。','条件は組み合わせて絞り込めます。記録をタップすると詳細・編集画面が開きます。')}<form class="card"><div class="two-columns"><label class="field">開始日<input type="date" name="from"></label><label class="field">終了日<input type="date" name="to"></label></div><label class="field">店舗<select name="store"><option value="">すべて</option><option value="__unset__">勤務未設定</option>${options(stores.map(s=>[s,s]))}</select></label><label class="field">商品カテゴリー<select name="category"><option value="">すべて</option>${options(ALL_CATEGORIES)}</select></label><label class="field">接客結果<select name="outcome"><option value="">すべて</option>${options(OUTCOMES)}</select></label><div class="two-columns"><label class="field">Panasonic提案<select name="proposal"><option value="">すべて</option><option value="yes">あり</option><option value="no">なし</option><option value="unknown">未記録</option></select></label><label class="field">店舗引継ぎ<select name="handoff"><option value="">すべて</option><option value="yes">あり</option><option value="no">なし</option><option value="unknown">未記録</option></select></label></div><button type="reset" class="button secondary">条件をクリア</button><p id="filter-error" role="alert" class="form-error" hidden></p></form><p id="match-count" role="status"></p><div id="matches"></div><button id="more-results" class="button secondary full spaced" hidden>さらに50件表示</button>`;
  const form=root.querySelector('form');let limit=50;
  function show(){const filters=Object.fromEntries(new FormData(form));const invalid=filters.from&&filters.to&&filters.from>filters.to;const error=root.querySelector('#filter-error');error.hidden=!invalid;error.textContent=invalid?'開始日は終了日以前にしてください。':'';const rows=invalid?[]:filterEncounters(db,filters);root.querySelector('#match-count').textContent=`${rows.length}件${rows.length>limit?`（${limit}件表示）`:''}`;root.querySelector('#matches').innerHTML=rows.length?encounterList(rows.slice(0,limit)):'<p class="empty">条件に合う接客はありません。</p>';root.querySelector('#more-results').hidden=rows.length<=limit;}
  form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('change',()=>{limit=50;show();});form.addEventListener('reset',()=>{setTimeout(()=>{limit=50;show();},0);});root.querySelector('#more-results').onclick=()=>{limit+=50;show();};show();
}
